import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Header } from "@/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <main className="">
        <div className="relative z-10 min-h-screen bg-black/50 bg-gradient-to-b from-black/60 via-transparent to-black/40">
          <Header />
        </div>

        <Image
          src="/images/hero.jpg"
          alt="Hero image"
          fill
          priority
          className="pointer-events-none absolute inset-0 select-none object-cover object-center"
        />
      </main>
    </>
  );
};

export default Home;
